config/routes.rb
Rails.application.routes.draw do

  resources :scenarios do
    collection do
      get 'get-restaurants'
    end
  end

  root 'starter#home'

  get 'configuration' => 'starter#configuration'
  get 'assessor' => 'assessor#home'
  get 'sample' => 'assessor#sample'

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base

  before_save {

    dummy = 'dummy@dummy.com'

    if email == dummy
      self.primary = false
    else
      email.downcase!
      self.primary = true
    end

    # Get the area details from Broadband Map - Census.gov
    if self.primary
      Parallel.each([1, 2], in_threads: 6) { |p|
        self.get_area_details if p == 1
        self.get_closer_zips if p == 2
      }
      self.get_nearby_businesses dummy
      self.load_reviews self.zomato_restaurant_id
    end

    true
  }

  before_destroy {
    unless self.nearby_restaurants.nil?
      eval(self.nearby_restaurants).each do |current_nearby|
        Scenario.where(primary: true).each do |other|
          unless other.nearby_restaurants.include? current_nearby
            Scenario.where(zomato_restaurant_id: current_nearby).destroy_all
          end
        end
      end
    end
  }

  # Get the area details from Broadband Map - Census.gov
  def get_area_details
    response = RestClient.get "http://www.broadbandmap.gov/broadbandmap/census/block?latitude=#{self.location_lat}&longitude=#{self.location_lng}&format=json"
    if response.code == 200
      response = JSON.parse(response)
      self.fips_block_type = response['Results']['block'][0]['geographyType']
      self.fips_state = response['Results']['block'][0]['FIPS'][1..2]
      self.fips_county = response['Results']['block'][0]['FIPS'][2..4]
      self.fips_tract = response['Results']['block'][0]['FIPS'][5..10]
      true
    end
    false
  end

  # Get the nearest zip codes from zipcodeAPI
  def get_closer_zips
    response = RestClient.get "https://www.zipcodeapi.com/rest/sAuK5UYivE54AQMykjxjPkmh3BCPaMiDnNnsImLd1RiCH5a1oHle2Iw5k8VuVe8i/radius.json/#{self.zomato_postal_code}/15/mile"
    if response.code == 200
      response = JSON.parse(response)
      closer_zips = []
      closer_zips_coords = []
      nearest_distance = 10

      Parallel.each(response['zip_codes'], in_threads: 8) { |zip_code|
        # Get the coordinates of each zip from Google Geocode API
        zip_coords = RestClient.get "https://maps.googleapis.com/maps/api/geocode/json?&address=#{zip_code['zip_code']}&key=AIzaSyDyKaPV4Oq0e5wpcKwyqV-hKolT1Bqc5vs"
        zip_coords = JSON.parse(zip_coords)
        if zip_coords['status'] == 'OK'
          # Get Distance from Google Distance Maps API
          distance = RestClient.get "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{self.location_lat},#{self.location_lng}&destinations=#{zip_coords["results"][0]["geometry"]["location"]["lat"]},#{zip_coords["results"][0]["geometry"]["location"]["lng"]}&key=AIzaSyDyKaPV4Oq0e5wpcKwyqV-hKolT1Bqc5vs"
          distance = JSON.parse(distance)
          if distance['status'] == 'OK' and distance['rows'][0]['elements'][0]['status'] == 'OK'
            distance = distance['rows'][0]['elements'][0]['distance']['value']*0.000621371
            if distance <= 5 and zip_code['zip_code'] != self.zomato_postal_code
              closer_zips.push zip_code['zip_code']
              closer_zips_coords.push "#{zip_coords['results'][0]['geometry']['location']['lat']},#{zip_coords['results'][0]['geometry']['location']['lng']}"
              if nearest_distance or nearest_distance > distance
                nearest_distance = distance
                self.nearest_zip = zip_code['zip_code'];
                self.nearest_zip_coords = "#{zip_coords['results'][0]['geometry']['location']['lat']},#{zip_coords['results'][0]['geometry']['location']['lng']}"
              end
            end
          end
        end
      }
      self.closer_zips = closer_zips.to_s
      self.closer_zips_coords = closer_zips_coords.to_s
      true
    end
    false
  end

  # Get the nearest restaurants from Zomato API (Max 20 Restaurants)
  def get_nearby_businesses(email)
    nearby_restaurants = []
    response = RestClient.get "https://developers.zomato.com/api/v2.1/search?q=#{self.zomato_cuisines}&lat=#{self.location_lat}&lon=#{self.location_lng}&radius=20000", accept: :json, 'user-key' => 'f9b94c7980f30bbc41833a1a0ed843ca'
    if response.code == 200
      response = JSON.parse(response)
      response['restaurants'].each do |item|
        if item['restaurant']['id'] != self.zomato_restaurant_id.to_s
          nearby_restaurants.push item['restaurant']['id']
          secondary_rest = Scenario.new
          secondary_rest = load_scenario secondary_rest, item
          secondary_rest.email = email
          secondary_rest.save
        end
      end
      self.nearby_restaurants = nearby_restaurants.to_s
      true
    end
    false
  end

  # Load new Restaurant to Scenario from Zomato JSON (Search API)
  def load_scenario(new_scenario, item)
    new_scenario.business_name = item['restaurant']['name']
    new_scenario.zomato_restaurant_id = item['restaurant']['id']
    new_scenario.location_lat = item['restaurant']['location']['latitude']
    new_scenario.location_lng = item['restaurant']['location']['longitude']
    new_scenario.zomato_address = item['restaurant']['location']['address']
    new_scenario.zomato_loc_city_id = item['restaurant']['location']['city_id']
    new_scenario.zomato_loc_city = item['restaurant']['location']['city']
    new_scenario.zomato_postal_code = item['restaurant']['location']['zipcode']
    new_scenario.zomato_cuisines = item['restaurant']['cuisines']
    new_scenario.zomato_user_rating = item['restaurant']['user_rating']['aggregate_rating']
    new_scenario.zomato_rating_text = item['restaurant']['user_rating']['rating_text']
    new_scenario.zomato_rating_color = item['restaurant']['user_rating']['rating_color']
    new_scenario.zomato_votes_count = item['restaurant']['user_rating']['votes']
    new_scenario.zomato_has_online_delivery = item['restaurant']['has_online_delivery']
    new_scenario.zomato_price_range = item['restaurant']['price_range']
    new_scenario.zomato_average_cost_for_two = item['restaurant']['average_cost_for_two']
    new_scenario.zomato_thumb = item['restaurant']['thumb']
    new_scenario
  end

  # Get reviews from Zomato
  def load_reviews(restaurant_id)
    response = RestClient.get "https://developers.zomato.com/api/v2.1/reviews?res_id=#{restaurant_id}", accept: :json, 'user-key' => 'f9b94c7980f30bbc41833a1a0ed843ca'
    if response.code == 200
      if response && response.length >= 2
        response = JSON.parse(response)
        response['user_reviews'].each do |review|
          new_review = Review.new
          new_review.review_rating = review['review']['rating']
          new_review.review_text = review['review']['review_text']
          new_review.rating_color = review['review']['rating_color']
          new_review.rating_text = review['review']['rating_text']
          new_review.review_time_stamp = review['review']['timestamp']
          new_review.likes = review['review']['likes']
          new_review.author_name = review['review']['user']['name']
          new_review.author_foodie_level = review['review']['user']['foodie_level']
          new_review.user_image = review['review']['user']['profile_image']
          new_review.comments_count = review['review']['comments_count']
          new_review.restaurant_id = restaurant_id
          new_review.save
        end
      end
    end
  end

  validates :business_name, presence: true, length: { maximum: 100 }
  validates :location_lat, presence: true
  validates :location_lng, presence: true
  validates :zomato_restaurant_id, presence: true,
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  layout "google-layout", only: [:new, :edit]
  before_action :set_scenario, only: [:show, :edit, :update, :destroy]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = Scenario.where(primary: true)
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    @reviews = Review.where(restaurant_id: @scenario.zomato_restaurant_id)
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
  end

  # GET /scenarios/1/edit
  def edit
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(scenario_params)

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html { redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /scenarios/get-restaurant-ids.json
  def get_restaurants
    term = params[:term]
    restaurant_list = []
    if term.length > 4
      response = RestClient.get "https://developers.zomato.com/api/v2.1/search?q=#{term}&count=5&lat=#{cookies[:lat]}&lon=#{cookies[:lng]}&radius=15000", accept: :json, 'user-key' => 'f9b94c7980f30bbc41833a1a0ed843ca'
      if response.code == 200
        response = JSON.parse(response)
        response['restaurants'].each do |item|
          restaurant_list.push({
             :label => item['restaurant']['name'] + ' at ' + item['restaurant']['location']['address'],
             :value => item['restaurant']['name'],
             :res_id => item['restaurant']['id'],
             :lat => item['restaurant']['location']['latitude'],
             :lng => item['restaurant']['location']['longitude'],
             :address => item['restaurant']['location']['address'],
             :city_id => item['restaurant']['location']['city_id'],
             :city => item['restaurant']['location']['city'],
             :postal_code => item['restaurant']['location']['zipcode'],
             :cuisines => item['restaurant']['cuisines'],
             :user_rating => item['restaurant']['user_rating']['aggregate_rating'],
             :rating_text => item['restaurant']['user_rating']['rating_text'],
             :rating_color => item['restaurant']['user_rating']['rating_color'],
             :votes_count => item['restaurant']['user_rating']['votes'],
             :has_online_delivery => item['restaurant']['has_online_delivery'],
             :price_range => item['restaurant']['price_range'],
             :average_cost_for_two => item['restaurant']['average_cost_for_two'],
             :thumb => item['restaurant']['thumb'],
          })
        end
      end
    end
    respond_to do |format|
      format.json { render :json => restaurant_list }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scenario_params
      params.require(:scenario).permit(:business_name, :email, :location_lat, :location_lng, :fips_state, :fips_county, :fips_tract, :fips_block_type, :zomato_postal_code, :zomato_category_id, :zomato_restaurant_id, :zomato_address, :zomato_cuisines, :zomato_establishment_id, :zomato_collection_id, :zomato_has_online_delivery, :zomato_reviews_count, :zomato_user_rating, :zomato_rating_text, :zomato_rating_color, :zomato_votes_count, :zomato_price_range, :zomato_average_cost_for_two, :zomato_thumb, :zomato_reviews, :zomato_geo_popularity, :zomato_geo_nightlife, :zomato_loc_entity_id, :zomato_loc_entity_type, :zomato_loc_city_id, :zomato_loc_city, :geo_locality, :closer_zips, :closer_zips_coords, :nearest_zip, :nearest_zip_coords)
    end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for @scenario, validate: true, html: {id: 'scenario-form'} do |f| %>
    <% if @scenario.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

          <ul>
            <% @scenario.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label :business_name %>
    <div class="field">
      <%= f.text_field :business_name, class: 'form-control' %>
    </div>
    <%= f.label :email %>
    <div class="field">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <%= f.label :location_lat %>
    <div class="field">
      <%= f.text_field :location_lat, class: 'form-control', readonly: 'readonly' %>
    </div>
    <%= f.label :location_lng %>
    <div class="field">
      <%= f.text_field :location_lng, class: 'form-control', readonly: 'readonly' %>
    </div>
    <%= f.label :zomato_restaurant_id %>
    <div class="field">
      <%= f.number_field :zomato_restaurant_id, class: 'form-control', readonly: 'readonly' %>
    </div>
    <%= f.label :zomato_address %>
    <div class="field">
      <%= f.text_area :zomato_address, class: 'form-control', readonly: 'readonly' %>
    </div>
    <%= f.label :zomato_cuisines %>
    <div class="field">
      <%= f.text_field :zomato_cuisines, class: 'form-control', readonly: 'readonly' %>
    </div>
    <%= f.label :zomato_user_rating %>
    <div class="field">
      <%= f.text_field :zomato_user_rating, class: 'form-control', readonly: 'readonly' %>
    </div><br>
    <!-- Hidden Fields -->
    <%= f.hidden_field :zomato_postal_code %>
    <%= f.hidden_field :zomato_loc_city_id %>
    <%= f.hidden_field :zomato_loc_city %>
    <%= f.hidden_field :zomato_rating_text %>
    <%= f.hidden_field :zomato_rating_color %>
    <%= f.hidden_field :zomato_votes_count %>
    <%= f.hidden_field :zomato_has_online_delivery %>
    <%= f.hidden_field :zomato_price_range %>
    <%= f.hidden_field :zomato_average_cost_for_two %>
    <%= f.hidden_field :zomato_thumb %>
    <!-- end of hidden fields -->
    <%= link_to 'Back', scenarios_path, class: 'btn btn-primary float-right' %>
    <div class="actions">
      <%= f.submit @scenario.new_record? ? 'Create' : 'Update', class: 'btn btn-success float-right mg-right-10' %>
    </div>
<% end %>

app/views/scenarios/edit.html.erb
<div class="col-md-4 float-right">
  <div class="ibox">
    <h1>Edit Scenario</h1>
    <br>
    <%= render 'form' %>
  </div>
</div>

app/views/scenarios/index.html.erb
<% if !notice.nil?  %>
    <p id="notice" class="alert alert-success text-center" role="alert"><%= notice %></p>
<% end %>
<h1>Available Scenarios</h1>
<br>

<table class="table">
  <thead>
    <tr>
      <th>Business name</th>
      <th>Cuisines</th>
      <th>User rating</th>
      <th>Address</th>
      <th>City</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.business_name %></td>
        <td><%= scenario.zomato_cuisines %></td>
        <td><%= scenario.zomato_user_rating %></td>
        <td><%= scenario.zomato_address %></td>
        <td><%= scenario.zomato_loc_city %></td>
        <td><%= link_to scenario do %>
            <i class="fa fa-list-alt"></i>
        <% end %></td>
        <td><%= link_to edit_scenario_path(scenario) do %>
            <i class="fa fa-pencil-square"></i>
        <% end %></td>
        <td><%= link_to scenario, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash"></i>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Scenario', new_scenario_path, 'class': 'btn btn-primary' %>

app/views/scenarios/new.html.erb
<div class="col-md-4 float-right">
    <div class="ibox">
      <h1>New Scenario</h1>
      <br>
      <%= render 'form' %>
    </div>
</div>

app/views/scenarios/show.html.erb
<% if !notice.nil?  %>
<p id="notice" class="alert alert-success text-center" role="alert"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-md-4">
    <div class="ibox">
      <h1> <%= @scenario.business_name %></h1><br>

      <div class="mg-left-5">
        <p>
          <strong>Email</strong><br>
          <%= @scenario.email %>
        </p>

        <p>
          <strong>Address</strong><br>
          <%= @scenario.zomato_address %>
        </p>

        <p>
          <strong>Cuisines</strong><br>
          <%= @scenario.zomato_cuisines %>
        </p>

        <p>
          <strong>Online delivery</strong><br>
          <%= @scenario.zomato_has_online_delivery %>
        </p>

        <p>
          <strong>Zomato user rating</strong><br>
          <%= @scenario.zomato_user_rating %>
        </p>

        <p>
          <strong>Zomato rating</strong><br>
          <%= @scenario.zomato_rating_text %>
        </p>

        <p id="loc_lat" hidden><%= @scenario.location_lat %></p>
        <p id="loc_lng" hidden><%= @scenario.location_lng %></p>

        <%= link_to 'Back', scenarios_path, class: 'btn btn-primary float-right' %>
        <%= link_to 'Edit', edit_scenario_path(@scenario), class: 'btn btn-success float-right mg-right-10' %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="google-map-small-container mg-bottom-20 mg-top-20">
      <div id="google-map"></div>
    </div>
    <!-- -->
    <% @reviews.each do |review| %>
        <div class="list-group">
          <%= link_to '', class: 'list-group-item' do %>
              <muted class="float-right">by <%= review.author_name + ' - ' + review.author_foodie_level %></muted>
              <h4 class="list-group-item-heading pd-bottom-5 u-border"><%= review.rating_text %><small> / <%= review.review_rating %></small></h4>
              <p><%= review.review_text %></p>
          <% end %>
        </div>
    <% end %>
    <!-- -->
  </div>
</div>